# This pipeline assumes that there is a Conda environment AzureRunner already.
# It will update to the full InnerEye environment, run pytest, and publish the test results.
steps:
  # To be quicker with environment creation, update the existing AzureRunner environment to contain all packages
  - bash: |
      conda env update --file environment.yml --name AzureRunner --quiet
      source activate AzureRunner
    displayName: Create InnerEye environment

  # The run ID of the training run is now available in most_recent_run.txt.
  - bash: |
      source activate AzureRunner
      pytest ./Tests/ -m "after_training" --junitxml=junit/test-results-after-training.xml
    env:
      PYTHONPATH: $(Build.SourcesDirectory)
      APPLICATION_KEY: $(InnerEyeDeepLearningServicePrincipalKey)
      BUILD_BRANCH: $(Build.SourceBranch)
    displayName: Run pytests that require training run

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: junit/test-results-after-training.xml
      testRunTitle: ${{parameters.test_run_title}}
    condition: succeededOrFailed()
    displayName: Publish test results ${{parameters.test_run_title}}
